package cep;

import java.util.List;

public interface CepRule {
	
	/**
	 * Get the rule's specification.
	 * @return
	 */
	public CepRuleDefinition getSpecification();
	
	/**
	 * Get the rule's incoming event types.
	 * @return
	 */
	public List<String> getIncomingEventTypes();
	
	/**
	 * Get the name of complex event type generated by this rule.
	 * @return
	 */
	public String getComplexEventType();
	
	/**
	 * Specifies the behavior when matched with a new <code>Event</code>.
	 * @param e
	 */
	public void match(Event e);

	/**
	 * Obtains the complex events generated by last invocation of the rule's 
	 * <code>match</code> method.
	 * @return The list of complex events
	 */
	public List<Event> getComplexEvents();
	
	/**
	 * Obtains the <code>CepRule</code> instances generated by last invocation of
	 * the rule's <code>match(Event e)</code> method.
	 * @return The list of new <code>CepRule</code> instances
	 */
	public List<CepRule> getNewRuleInstances();
	
	/**
	 * Specifies how to set the parameters of this rule.
	 * @param paramName
	 * @param value
	 */
	public void setParameter(String paramName, Object value);
	
	
}
